# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-18 19:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=150)),
                ('image_path', pyuploadcare.dj.models.ImageField(blank=True)),
                ('image_caption', models.CharField(max_length=255)),
                ('likes', models.IntegerField(default=0)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('comments', models.IntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Profile')),
            ],
            options={
                'ordering': ['upload_date'],
            },
        ),
    ]
